/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.UI;

import com.dao.NguoiDungDAO;
import com.entity.NguoiDung;
import util.setColorSystem;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;
import util.Auth;
import util.MsgBox;
//import sun.lwawt.macosx.CocoaConstants;

public class DangNhap extends javax.swing.JFrame {

    public DangNhap() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0, 0, 0, 0));
        //  jPanel1.setBackground(new Color(232,232,232));
        this.mouseHover();
        lblIconAn.setVisible(false);
        lblAnMK.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDangNhap = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblDangNhap = new javax.swing.JLabel();
        txtTenDN = new javax.swing.JTextField();
        lblQuenMK = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        lblDangKy = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        lblIconAn = new javax.swing.JLabel();
        lblAnMK = new javax.swing.JLabel();
        lblHienmk = new javax.swing.JLabel();
        lblIconHien = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        btnDangNhap.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setPreferredSize(new java.awt.Dimension(114, 30));
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(217, 228, 221));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDangNhap.setBackground(new java.awt.Color(102, 102, 102));
        lblDangNhap.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblDangNhap.setText("Tên đăng nhập:");
        jPanel1.add(lblDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        txtTenDN.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtTenDN.setAlignmentX(1.0F);
        txtTenDN.setAlignmentY(1.0F);
        txtTenDN.setBorder(null);
        txtTenDN.setPreferredSize(new java.awt.Dimension(266, 30));
        txtTenDN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenDNKeyPressed(evt);
            }
        });
        jPanel1.add(txtTenDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 280, -1));

        lblQuenMK.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblQuenMK.setForeground(new java.awt.Color(0, 102, 255));
        lblQuenMK.setText("<html> <body> <u>Đổi mật khẩu ?</u> </body> </html>");
        lblQuenMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuenMKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuenMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuenMKMouseExited(evt);
            }
        });
        jPanel1.add(lblQuenMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        lblMatKhau.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblMatKhau.setText("Mật khẩu:");
        jPanel1.add(lblMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        lblDangKy.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblDangKy.setForeground(new java.awt.Color(0, 102, 255));
        lblDangKy.setText("<html> <body> <u>Bạn chưa có tài khoản ?</u> </body> </html>");
        lblDangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangKyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDangKyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDangKyMouseExited(evt);
            }
        });
        jPanel1.add(lblDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, 30));

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        jPanel1.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/accounting.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/DangNhap.png"))); // NOI18N
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoginMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginMouseEntered(evt);
            }
        });
        jPanel1.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        txtMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMatKhauKeyReleased(evt);
            }
        });
        jPanel1.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 280, 30));

        lblIconAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/invisible_24px.png"))); // NOI18N
        lblIconAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconAnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblIconAnMousePressed(evt);
            }
        });
        jPanel1.add(lblIconAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 30));

        lblAnMK.setForeground(new java.awt.Color(0, 102, 255));
        lblAnMK.setText("Ẩn mật khẩu");
        lblAnMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAnMKMousePressed(evt);
            }
        });
        jPanel1.add(lblAnMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 90, 30));

        lblHienmk.setForeground(new java.awt.Color(0, 102, 255));
        lblHienmk.setText("Hiện mật khẩu");
        lblHienmk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHienmkMousePressed(evt);
            }
        });
        jPanel1.add(lblHienmk, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 90, 30));

        lblIconHien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/eye_24px.png"))); // NOI18N
        lblIconHien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconHienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconHienMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblIconHienMousePressed(evt);
            }
        });
        jPanel1.add(lblIconHien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 350, 490));

        jPanel2.setBackground(new java.awt.Color(210, 245, 227));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMinimumSize(new java.awt.Dimension(290, 380));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/saving.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 250, 340));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/Path 1.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblExit);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblExit);
    }//GEN-LAST:event_lblExitMouseExited

    private void lblQuenMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMKMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setColor(lblQuenMK);
    }//GEN-LAST:event_lblQuenMKMouseEntered

    private void lblQuenMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMKMouseExited
        setColorSystem cl = new setColorSystem();
        cl.resetColor(lblQuenMK);
    }//GEN-LAST:event_lblQuenMKMouseExited

    private void lblDangKyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangKyMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setColor(lblDangKy);
    }//GEN-LAST:event_lblDangKyMouseEntered

    private void lblDangKyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangKyMouseExited
        setColorSystem cl = new setColorSystem();
        cl.resetColor(lblDangKy);
    }//GEN-LAST:event_lblDangKyMouseExited

    private void lblDangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangKyMouseClicked
        new DangKy().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblDangKyMouseClicked

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed

    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void txtTenDNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenDNKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            System.exit(0);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dangNhap();
        }
    }//GEN-LAST:event_txtTenDNKeyPressed

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        dangNhap();
    }//GEN-LAST:event_lblLoginMouseClicked

    private void lblLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblLogin);
    }//GEN-LAST:event_lblLoginMouseEntered

    private void lblLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseExited
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblLogin);
    }//GEN-LAST:event_lblLoginMouseExited

    private void txtMatKhauKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            System.exit(0);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dangNhap();
        }
    }//GEN-LAST:event_txtMatKhauKeyReleased

    private void lblIconAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconAnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconAnMouseClicked

    private void lblIconHienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHienMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconHienMouseClicked

    private void lblIconHienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHienMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblIconHienMouseEntered

    private void lblIconHienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHienMousePressed
        // TODO add your handling code here:
        HienMK();
    }//GEN-LAST:event_lblIconHienMousePressed

    private void lblIconAnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconAnMousePressed
        // TODO add your handling code here:
        AnMk();
    }//GEN-LAST:event_lblIconAnMousePressed

    private void lblAnMKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnMKMousePressed
        // TODO add your handling code here:
        AnMk();
    }//GEN-LAST:event_lblAnMKMousePressed

    private void lblHienmkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHienmkMousePressed
        // TODO add your handling code here:
        HienMK();
    }//GEN-LAST:event_lblHienmkMousePressed

    private void lblQuenMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMKMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblQuenMKMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAnMK;
    private javax.swing.JLabel lblDangKy;
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblHienmk;
    private javax.swing.JLabel lblIconAn;
    private javax.swing.JLabel lblIconHien;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblQuenMK;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables

    public void mouseHover() {
        lblQuenMK.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblDangKy.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnDangNhap.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblExit.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }
    NguoiDungDAO ngdao = new NguoiDungDAO();

    public void openDangNhap() {
        new DangNhap().setVisible(true);
    }

    void dangNhap() {
        String manv = txtTenDN.getText().trim();
        String matKhau = txtMatKhau.getText();
        NguoiDung nguoidung = ngdao.selectByid(manv);
        if (nguoidung == null) {
            MsgBox.alert(this, "Sai ten dang nhap");
        } else if (!matKhau.equals(nguoidung.getMatKhau())) {
            MsgBox.alert(this, "Sai mat khau");
        } else {
            Auth.user = nguoidung;
            new QuanLy().setVisible(true);
            this.dispose();
        }
    }
    void AnMk(){
        lblIconAn.setVisible(false);
        lblAnMK.setVisible(false);
        lblIconHien.setVisible(true);
        lblHienmk.setVisible(true);
        txtMatKhau.setEchoChar('*');
    }
    void HienMK(){
        lblIconHien.setVisible(false);
        lblHienmk.setVisible(false);
        lblIconAn.setVisible(true);
        lblAnMK.setVisible(true);
        txtMatKhau.setEchoChar((char)0);
    }
}
