/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.UI;

import com.dao.LichSuDAO;
import com.dao.MucTieuTietKiemDAO;
import com.dao.NguoiDungDAO;
import com.dao.ThongKe_ThuChi_DAO;
import com.dao.ThuChiDAO;
import com.entity.MucTieu;
import com.entity.NguoiDung;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.AxisLocation;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.labels.StandardCategoryToolTipGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.DatasetRenderingOrder;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import util.Auth;
import util.MsgBox;
import util.setColorSystem;
import utils.fmDate;

/**
 *
 * @author trantrung
 */
public class QuanLy extends javax.swing.JFrame {

    /**
     * Creates new form QuanLy
     */
    public QuanLy() {
        initComponents();
        init();
        tblDanhSach.getTableHeader().setOpaque(false);
        tblDanhSach.getTableHeader().setBackground(new Color(249, 247, 207));
        tblLichSu.getTableHeader().setOpaque(false);
        tblLichSu.getTableHeader().setBackground(new Color(249, 247, 207));
        tblThuChi.getTableHeader().setOpaque(false);
        tblThuChi.getTableHeader().setBackground(new Color(249, 247, 207));
        NguoiDung nd = ndDAO.selectByid(Auth.user.getUser());
        lblSoDu.setText(String.valueOf(nd.getSoDu()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        deleteRow = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlBg = new javax.swing.JPanel();
        pnlleft = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlKeHoach = new javax.swing.JPanel();
        lblLogoQL = new javax.swing.JLabel();
        lblQuanLy = new javax.swing.JLabel();
        pnlThongTinND = new javax.swing.JPanel();
        lblThongTinND = new javax.swing.JLabel();
        lblLogoGD2 = new javax.swing.JLabel();
        pnlThongKe = new javax.swing.JPanel();
        lblThuChi1 = new javax.swing.JLabel();
        lblLogoGD1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        pnlTabs = new javax.swing.JPanel();
        pnlTab4 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        lblThemGiaoDich = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThuChi = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        pnlTab1 = new javax.swing.JPanel();
        pnltop = new javax.swing.JPanel();
        lblTenMT = new javax.swing.JLabel();
        lblTenMT1 = new javax.swing.JLabel();
        lblTenMT2 = new javax.swing.JLabel();
        txtTenMTK = new javax.swing.JTextField();
        txtGiaTri = new javax.swing.JTextField();
        cboThoiGianTK = new javax.swing.JComboBox<>();
        pnlButton = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JLabel();
        btnSua = new javax.swing.JLabel();
        btnXoa = new javax.swing.JLabel();
        btnTietKiem = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlbottom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblMucTietKiem = new javax.swing.JLabel();
        cboMucTietKiem = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        pgbTienDo = new javax.swing.JProgressBar();
        lblTienDaTK = new javax.swing.JLabel();
        txtTienDaTK = new javax.swing.JTextField();
        lblThoiGianCon = new javax.swing.JLabel();
        txtThoiGian = new javax.swing.JTextField();
        lblNgayConLai = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlPieChart = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlTab3 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLichSu = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        lblQuenMK = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtSoDu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        txtHoTen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIDNguoiDung = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSoDu = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();

        deleteRow.setText("jMenuItem1");
        jPopupMenu1.add(deleteRow);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBg.setBackground(new java.awt.Color(219, 246, 233));
        pnlBg.setPreferredSize(new java.awt.Dimension(700, 474));
        pnlBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlleft.setBackground(new java.awt.Color(154, 211, 188));
        pnlleft.setPreferredSize(new java.awt.Dimension(150, 100));
        pnlleft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/pages.png"))); // NOI18N
        pnlleft.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        pnlKeHoach.setBackground(new java.awt.Color(154, 211, 188));
        pnlKeHoach.setPreferredSize(new java.awt.Dimension(150, 40));
        pnlKeHoach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlKeHoachMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlKeHoachMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlKeHoachMouseEntered(evt);
            }
        });
        pnlKeHoach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoQL.setBackground(new java.awt.Color(255, 255, 255));
        lblLogoQL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/wallet.png"))); // NOI18N
        pnlKeHoach.add(lblLogoQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 40));

        lblQuanLy.setBackground(new java.awt.Color(204, 204, 204));
        lblQuanLy.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        lblQuanLy.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLy.setText("Quản lý mục tk");
        pnlKeHoach.add(lblQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 40));

        pnlleft.add(pnlKeHoach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 190, 40));

        pnlThongTinND.setBackground(new java.awt.Color(154, 211, 188));
        pnlThongTinND.setPreferredSize(new java.awt.Dimension(150, 40));
        pnlThongTinND.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThongTinNDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlThongTinNDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlThongTinNDMouseExited(evt);
            }
        });
        pnlThongTinND.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThongTinND.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        lblThongTinND.setForeground(new java.awt.Color(255, 255, 255));
        lblThongTinND.setText("Thông tin ND");
        pnlThongTinND.add(lblThongTinND, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 130, -1));

        lblLogoGD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/kyc (1).png"))); // NOI18N
        pnlThongTinND.add(lblLogoGD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pnlleft.add(pnlThongTinND, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 190, 40));

        pnlThongKe.setBackground(new java.awt.Color(154, 211, 188));
        pnlThongKe.setPreferredSize(new java.awt.Dimension(150, 40));
        pnlThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseEntered(evt);
            }
        });
        pnlThongKe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThuChi1.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        lblThuChi1.setForeground(new java.awt.Color(255, 255, 255));
        lblThuChi1.setText("Quản lý chi tiêu");
        pnlThongKe.add(lblThuChi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 130, -1));

        lblLogoGD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/money-transfer.png"))); // NOI18N
        pnlThongKe.add(lblLogoGD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pnlleft.add(pnlThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 190, 40));

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlleft.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        pnlBg.add(pnlleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 590));

        pnlTabs.setLayout(new java.awt.CardLayout());

        jTabbedPane3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        lblThemGiaoDich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/ThemGD.png"))); // NOI18N
        lblThemGiaoDich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThemGiaoDichMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThemGiaoDichMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThemGiaoDichMouseExited(evt);
            }
        });

        tblThuChi.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        tblThuChi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên giao dịch", "Ngày", "Số tiền", "Loại giao dịch"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThuChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThuChiMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblThuChiMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblThuChi);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblThemGiaoDich)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lblThemGiaoDich)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Giao Dịch", jPanel6);

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new java.awt.BorderLayout());
        jTabbedPane3.addTab("Thống kê Thu/Chi", jPanel4);

        javax.swing.GroupLayout pnlTab4Layout = new javax.swing.GroupLayout(pnlTab4);
        pnlTab4.setLayout(pnlTab4Layout);
        pnlTab4Layout.setHorizontalGroup(
            pnlTab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTab4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        pnlTab4Layout.setVerticalGroup(
            pnlTab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTab4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        pnlTabs.add(pnlTab4, "card2");

        jTabbedPane2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        pnltop.setBackground(new java.awt.Color(219, 246, 233));
        pnltop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTenMT.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblTenMT.setForeground(new java.awt.Color(51, 51, 51));
        lblTenMT.setText("Thời gian tiết kiệm:");
        pnltop.add(lblTenMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 30));

        lblTenMT1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblTenMT1.setForeground(new java.awt.Color(51, 51, 51));
        lblTenMT1.setText("Tên mục tiết kiệm:");
        pnltop.add(lblTenMT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblTenMT2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblTenMT2.setForeground(new java.awt.Color(51, 51, 51));
        lblTenMT2.setText("Giá trị:");
        pnltop.add(lblTenMT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 91, -1, 30));

        txtTenMTK.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtTenMTK.setPreferredSize(new java.awt.Dimension(140, 24));
        pnltop.add(txtTenMTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, 30));

        txtGiaTri.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtGiaTri.setPreferredSize(new java.awt.Dimension(140, 24));
        pnltop.add(txtGiaTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 140, 30));

        cboThoiGianTK.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        cboThoiGianTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 tháng", "3 tháng", "6 tháng", "12 tháng" }));
        pnltop.add(cboThoiGianTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 140, 30));

        pnlButton.setBackground(new java.awt.Color(219, 246, 233));
        pnlButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(219, 246, 233));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pnlButton.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/Group 2.png"))); // NOI18N
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemMouseExited(evt);
            }
        });
        pnlButton.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 40, 90, -1));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/createMT – 1.png"))); // NOI18N
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuaMouseExited(evt);
            }
        });
        pnlButton.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/createMT – 2.png"))); // NOI18N
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaMouseExited(evt);
            }
        });
        pnlButton.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        btnTietKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/Group 1_1.png"))); // NOI18N
        btnTietKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTietKiemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTietKiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTietKiemMouseExited(evt);
            }
        });
        pnlButton.add(btnTietKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 150, 130, -1));

        pnltop.add(pnlButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 170, 190));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/tag.png"))); // NOI18N
        pnltop.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/market-investment.png"))); // NOI18N
        pnltop.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/calendar.png"))); // NOI18N
        pnltop.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        pnlbottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDanhSach.setBackground(new java.awt.Color(204, 204, 204));
        tblDanhSach.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên mục tiêt kiệm", "Giá trị", "Thời gian tiết kiệm", "Số tiền đã tiết kiệm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);

        javax.swing.GroupLayout pnlTab1Layout = new javax.swing.GroupLayout(pnlTab1);
        pnlTab1.setLayout(pnlTab1Layout);
        pnlTab1Layout.setHorizontalGroup(
            pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTab1Layout.createSequentialGroup()
                .addComponent(pnltop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTab1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlbottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlTab1Layout.setVerticalGroup(
            pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTab1Layout.createSequentialGroup()
                .addComponent(pnltop, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTab1Layout.createSequentialGroup()
                    .addGap(0, 404, Short.MAX_VALUE)
                    .addComponent(pnlbottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 158, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Tích luỹ", pnlTab1);

        jPanel3.setBackground(new java.awt.Color(219, 246, 233));

        lblMucTietKiem.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblMucTietKiem.setText("Mục tiết kiệm:");

        cboMucTietKiem.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        cboMucTietKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMucTietKiemActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(219, 246, 233));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pgbTienDo.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        pgbTienDo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pgbTienDo.setEnabled(false);
        pgbTienDo.setPreferredSize(new java.awt.Dimension(146, 200));
        pgbTienDo.setStringPainted(true);

        lblTienDaTK.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblTienDaTK.setText("Số tiền đã tiết kiệm được:");

        txtTienDaTK.setEditable(false);
        txtTienDaTK.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        lblThoiGianCon.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblThoiGianCon.setText("Tiết kiệm đến ngày:");

        txtThoiGian.setEditable(false);
        txtThoiGian.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        lblNgayConLai.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblNgayConLai.setText("ngày");

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel4.setText("Tiến độ:");

        pnlPieChart.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlPieChart.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel2.setText("Ngày còn lại:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTienDaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThoiGianCon)
                    .addComponent(jLabel4)
                    .addComponent(pgbTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNgayConLai))
                    .addComponent(lblTienDaTK))
                .addGap(24, 24, 24)
                .addComponent(pnlPieChart, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(pgbTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblTienDaTK)
                .addGap(18, 18, 18)
                .addComponent(txtTienDaTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblThoiGianCon)
                .addGap(18, 18, 18)
                .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayConLai)
                    .addComponent(jLabel2))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPieChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblMucTietKiem)
                .addGap(35, 35, 35)
                .addComponent(cboMucTietKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMucTietKiem)
                    .addComponent(cboMucTietKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Thống kê mục tiết kiệm", jPanel3);

        pnlTab3.setBackground(new java.awt.Color(219, 246, 233));

        txtTimKiem.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        btnTimKiem.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tblLichSu.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        tblLichSu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mục tiết kiệm", "Ngày ", "Số tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblLichSu);

        javax.swing.GroupLayout pnlTab3Layout = new javax.swing.GroupLayout(pnlTab3);
        pnlTab3.setLayout(pnlTab3Layout);
        pnlTab3Layout.setHorizontalGroup(
            pnlTab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTab3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addGroup(pnlTab3Layout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimKiem)))
                .addContainerGap())
        );
        pnlTab3Layout.setVerticalGroup(
            pnlTab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTab3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Lịch sử", pnlTab3);

        pnlTabs.add(jTabbedPane2, "card1");

        jPanel5.setBackground(new java.awt.Color(219, 246, 233));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblQuenMK.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblQuenMK.setForeground(new java.awt.Color(0, 102, 255));
        lblQuenMK.setText("<html> <body> <u>Đổi mật khẩu ?</u> </body> </html>");
        lblQuenMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuenMKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuenMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuenMKMouseExited(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtSoDu.setEditable(false);
        txtSoDu.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel9.setText("Số Dư:");

        btnSave.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel8.setText("Giới tính:");

        buttonGroup1.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        rdoNu.setText("Nữ");

        txtHoTen.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel7.setText("Họ tên:");

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel10.setText("IDNguoiDung:");

        txtIDNguoiDung.setEditable(false);
        txtIDNguoiDung.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoDu, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(rdoNam)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoNu))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIDNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnSave)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtIDNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rdoNam)
                    .addComponent(rdoNu))
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoDu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(60, 60, 60)
                .addComponent(btnSave)
                .addGap(64, 64, 64))
        );

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel11.setText("Thông tin tài khoản");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/kyc.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(lblQuenMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel11)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(lblQuenMK, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlTabs.add(jPanel5, "card3");

        pnlBg.add(pnlTabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 620, 530));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel1.setText("Số dư:");
        pnlBg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        lblSoDu.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        lblSoDu.setForeground(new java.awt.Color(51, 51, 255));
        lblSoDu.setText("000");
        pnlBg.add(lblSoDu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 206, 20));

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
        });
        pnlBg.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, 30));

        getContentPane().add(pnlBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 810, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlKeHoachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKeHoachMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setColor(pnlKeHoach);
    }//GEN-LAST:event_pnlKeHoachMouseEntered

    private void pnlKeHoachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKeHoachMouseExited
        setColorSystem cl = new setColorSystem();
        cl.resetColor(pnlKeHoach);
    }//GEN-LAST:event_pnlKeHoachMouseExited

    private void pnlKeHoachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKeHoachMouseClicked
        cardLayout.show(pnlTabs, "card1");
        pieChartMTK();
        if (tblDanhSach.getRowCount() <= 0) {
            new HuongDanMTK(this, true).setVisible(true);
        }
    }//GEN-LAST:event_pnlKeHoachMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblExit);
    }//GEN-LAST:event_lblExitMouseExited

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblExit);
    }//GEN-LAST:event_lblExitMouseEntered

    private void pnlThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setColor(pnlThongKe);
    }//GEN-LAST:event_pnlThongKeMouseEntered

    private void pnlThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseExited
        setColorSystem cl = new setColorSystem();
        cl.resetColor(pnlThongKe);
    }//GEN-LAST:event_pnlThongKeMouseExited

    private void pnlThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseClicked
        cardLayout.show(pnlTabs, "card2");
        barChartThuChi();
        if (tblThuChi.getRowCount() <= 0) {
            new HuongDanGiaoDich(this, true).setVisible(true);
        }
    }//GEN-LAST:event_pnlThongKeMouseClicked

    private void btnThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setBorder(btnThem);
    }//GEN-LAST:event_btnThemMouseEntered

    private void btnThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseExited
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(btnThem);
    }//GEN-LAST:event_btnThemMouseExited

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        if (checkError()) {
            addMtkToDaTaBase();
        }
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnSuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setBorder(btnSua);
    }//GEN-LAST:event_btnSuaMouseEntered

    private void btnSuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseExited
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(btnSua);
    }//GEN-LAST:event_btnSuaMouseExited

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        if (checkError()) {
            updateMtkToDaTaBase();
        }
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setBorder(btnXoa);
    }//GEN-LAST:event_btnXoaMouseEntered

    private void btnXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseExited
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(btnXoa);
    }//GEN-LAST:event_btnXoaMouseExited

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        deleteMtk();
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnTietKiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTietKiemMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setBorder(btnTietKiem, 240, 84, 84);
    }//GEN-LAST:event_btnTietKiemMouseEntered

    private void btnTietKiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTietKiemMouseExited

        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(btnTietKiem);
    }//GEN-LAST:event_btnTietKiemMouseExited

    private void btnTietKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTietKiemMouseClicked
        new TietKiem().setVisible(true);
    }//GEN-LAST:event_btnTietKiemMouseClicked

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        selectForm();
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void cboMucTietKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMucTietKiemActionPerformed
        if (cboMucTietKiem.getSelectedIndex() != -1) {
            caCuLateDates();
        }
    }//GEN-LAST:event_cboMucTietKiemActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        fillTableLichSu();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        barChartThuChi();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void lblThemGiaoDichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemGiaoDichMouseClicked
        new GiaoDich().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblThemGiaoDichMouseClicked

    private void lblThemGiaoDichMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemGiaoDichMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblThemGiaoDich, 0, 0, 0);
    }//GEN-LAST:event_lblThemGiaoDichMouseEntered

    private void lblThemGiaoDichMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemGiaoDichMouseExited
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblThemGiaoDich);
    }//GEN-LAST:event_lblThemGiaoDichMouseExited

    private void tblThuChiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThuChiMouseReleased
        final JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem deleteItem = new JMenuItem("Delete");
        deleteItem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                xoaGiaoDich();
            }
        });
        popupMenu.add(deleteItem);
        tblThuChi.setComponentPopupMenu(popupMenu);

    }//GEN-LAST:event_tblThuChiMouseReleased

    private void tblThuChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThuChiMouseClicked

    }//GEN-LAST:event_tblThuChiMouseClicked

    private void pnlThongTinNDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongTinNDMouseClicked
        cardLayout.show(pnlTabs, "card3");
    }//GEN-LAST:event_pnlThongTinNDMouseClicked

    private void pnlThongTinNDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongTinNDMouseExited
        setColorSystem cl = new setColorSystem();
        cl.resetColor(pnlThongTinND);
    }//GEN-LAST:event_pnlThongTinNDMouseExited

    private void pnlThongTinNDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongTinNDMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setColor(pnlThongTinND);
    }//GEN-LAST:event_pnlThongTinNDMouseEntered

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       upDateInFoND();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void lblQuenMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMKMouseClicked
        // TODO add your handling code here:
        new DoiMatKhau().setVisible(true);
    }//GEN-LAST:event_lblQuenMKMouseClicked

    private void lblQuenMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMKMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setColor(lblQuenMK);
    }//GEN-LAST:event_lblQuenMKMouseEntered

    private void lblQuenMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMKMouseExited
        setColorSystem cl = new setColorSystem();
        cl.resetColor(lblQuenMK);
    }//GEN-LAST:event_lblQuenMKMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new QuanLy().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel btnSua;
    private javax.swing.JLabel btnThem;
    private javax.swing.JLabel btnTietKiem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboMucTietKiem;
    private javax.swing.JComboBox<String> cboThoiGianTK;
    private javax.swing.JMenuItem deleteRow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoGD1;
    private javax.swing.JLabel lblLogoGD2;
    private javax.swing.JLabel lblLogoQL;
    private javax.swing.JLabel lblMucTietKiem;
    private javax.swing.JLabel lblNgayConLai;
    private javax.swing.JLabel lblQuanLy;
    private javax.swing.JLabel lblQuenMK;
    private javax.swing.JLabel lblSoDu;
    private javax.swing.JLabel lblTenMT;
    private javax.swing.JLabel lblTenMT1;
    private javax.swing.JLabel lblTenMT2;
    private javax.swing.JLabel lblThemGiaoDich;
    private javax.swing.JLabel lblThoiGianCon;
    private javax.swing.JLabel lblThongTinND;
    private javax.swing.JLabel lblThuChi1;
    private javax.swing.JLabel lblTienDaTK;
    private javax.swing.JProgressBar pgbTienDo;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlKeHoach;
    private javax.swing.JPanel pnlPieChart;
    private javax.swing.JPanel pnlTab1;
    private javax.swing.JPanel pnlTab3;
    private javax.swing.JPanel pnlTab4;
    private javax.swing.JPanel pnlTabs;
    private javax.swing.JPanel pnlThongKe;
    private javax.swing.JPanel pnlThongTinND;
    private javax.swing.JPanel pnlbottom;
    private javax.swing.JPanel pnlleft;
    private javax.swing.JPanel pnltop;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTable tblLichSu;
    private javax.swing.JTable tblThuChi;
    private javax.swing.JTextField txtGiaTri;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtIDNguoiDung;
    private javax.swing.JTextField txtSoDu;
    private javax.swing.JTextField txtTenMTK;
    private javax.swing.JTextField txtThoiGian;
    private javax.swing.JTextField txtTienDaTK;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    //Variables
    CardLayout cardLayout;
    MucTieuTietKiemDAO mtkDAO = new MucTieuTietKiemDAO();
    LichSuDAO lsDAO = new LichSuDAO();
    ThongKe_ThuChi_DAO tkctDAO = new ThongKe_ThuChi_DAO();
    NguoiDungDAO ndDAO = new NguoiDungDAO();
    ThuChiDAO tcDAO = new ThuChiDAO();

    void init() {
        this.setResizable(true);
        this.setLocationRelativeTo(null);
//        this.setBackground(new Color(0, 0, 0, 0));
//        pnlBg.setBackground(new Color(0, 0, 0, 0));
        cardLayout = (CardLayout) pnlTabs.getLayout();
        fillTableMucTietKiem();
        fillComboBoxMTK();
        mouseHover();
        fillTableLichSu();
        fillTableChiThu();
        getInFoND();

    }

    public void mouseHover() {
        pnlKeHoach.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        pnlThongKe.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        pnlThongTinND.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    public void clear() {
        txtTenMTK.setText("");
        txtThoiGian.setText("");
        txtTienDaTK.setText("");
        txtGiaTri.setText("");
        cboThoiGianTK.setSelectedIndex(0);
    }

    //Kiểm lỗi
    boolean checkError() {
        if (txtGiaTri.getText().matches(".*[a-zA-Z].*")) {
            MsgBox.alert(this, "Khong dc dien ki tu vao o gia tri");
            return false;
        } else if (txtTenMTK.getText().equals("") || txtGiaTri.getText().equals("")) {
            MsgBox.alert(this, "khong duoc de trong");
            return false;
        } else if (Double.valueOf(txtGiaTri.getText()) < 0) {
            MsgBox.alert(this, "khong duoc nhap so am");
            return false;
        }
        return true;
    }

    //filltable
    public void fillTableMucTietKiem() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSach.getModel();
        model.setRowCount(0);
        try {
            List<MucTieu> list = mtkDAO.selectMTK(Auth.user.getUser());
            for (MucTieu mt : list) {
                Object row[] = {
                    mt.getIdMucTieu(), mt.getTenMucTieu(), String.format("%.0f", mt.getGiaTri()) + " VND", mt.getThoiHan() + " tháng", mt.getSoTienDaTK()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Loi truy van du lieu");
            e.printStackTrace();
        }
    }

    public void fillTableLichSu() {
        DefaultTableModel model = (DefaultTableModel) tblLichSu.getModel();
        model.setRowCount(0);
        if (txtTimKiem.getText().equals("")) {
            try {
                List<Object[]> list = tkctDAO.getLichSu(Auth.user.getUser());
                for (Object[] ls : list) {
                    model.addRow(ls);
                }
                tblLichSu.setModel(model);
            } catch (Exception e) {
                MsgBox.alert(this, "Loi truy van du lieu");
                e.printStackTrace();
            }
        } else {
            try {
                List<Object[]> list = tkctDAO.getLichSu1(Auth.user.getUser(), txtTimKiem.getText().trim());
                for (Object[] ls : list) {
                    model.addRow(ls);
                }
            } catch (Exception e) {
                MsgBox.alert(this, "Loi truy van du lieu");
                e.printStackTrace();
            }
        }
    }

    void fillTableChiThu() {
        DefaultTableModel model = (DefaultTableModel) tblThuChi.getModel();
        model.setRowCount(0);
        try {
            List<Object[]> list = tkctDAO.LichSu_ThuChi(Auth.user.getUser().trim());
            for (Object[] ls : list) {
                model.addRow(ls);
            }
            tblThuChi.setModel(model);
        } catch (Exception e) {
            MsgBox.alert(this, "Loi truy van du lieu");
            e.printStackTrace();
        }
    }

    public void fillComboBoxMTK() {
        DefaultComboBoxModel combobox = (DefaultComboBoxModel) cboMucTietKiem.getModel();
        combobox.removeAllElements();
        List<MucTieu> list = mtkDAO.selectMTK(Auth.user.getUser());
        for (MucTieu mt : list) {
            combobox.addElement(mt);
        }
    }

    //Tuỳ chình Mục tiết kiệm
    public void addMtkToDaTaBase() {
        MucTieu mt = getInFo();
        try {
            mtkDAO.insert(mt);
            clear();
            fillTableMucTietKiem();
            fillComboBoxMTK();
        } catch (Exception e) {
            MsgBox.alert(this, "Loi roi ku");
        }
    }

    public void updateMtkToDaTaBase() {
        MucTieu mt = upDateInFo();
        try {
            mtkDAO.update(mt);
            fillTableMucTietKiem();
            clear();
        } catch (Exception e) {
            MsgBox.alert(this, "Loi roi ku");
        }
    }

    public void deleteMtk() {
        if (Auth.user.getUser().equals("")) {
            MsgBox.alert(this, "Dang nhap de co the xoa");
        } else if (MsgBox.confirm(this, "That su muon xoa ?")) {
            try {
                int row = (int) (tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 0));
                mtkDAO.delete(row);
                MsgBox.alert(this, "Xoa thanh cong");
                fillTableMucTietKiem();
                fillComboBoxMTK();
            } catch (Exception e) {
                MsgBox.alert(this, "Loi roi ku");
                e.printStackTrace();
            }
        }
    }

    MucTieu getInFo() {
        MucTieu mt = new MucTieu();
        String arr = (String) cboThoiGianTK.getSelectedItem();
        String ar[] = arr.split(" ");
        mt.setUsername(Auth.user.getUser());
        mt.setTenMucTieu(txtTenMTK.getText());
        mt.setGiaTri(Double.parseDouble(txtGiaTri.getText()));
        mt.setThoiHan(Integer.valueOf(ar[0]));
        return mt;
    }

    MucTieu upDateInFo() {
        MucTieu mt = new MucTieu();
        String arr = (String) cboThoiGianTK.getSelectedItem();
        String ar[] = arr.split(" ");
        try {
            mt.setUsername(Auth.user.getUser());
            mt.setTenMucTieu(txtTenMTK.getText());
            mt.setGiaTri(Double.valueOf(txtGiaTri.getText()));
            mt.setThoiHan(Integer.valueOf(ar[0]));
            double value = (double) tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 4);
            mt.setSoTienDaTK(value);
            int id = (int) tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 0);
            System.out.println(id);
            mt.setIdMucTieu(id);
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật lỗi, vui lòng thử lại");
            e.printStackTrace();
        }
        return mt;
    }

    void selectForm() {
        int id = (int) tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 0);
        String User = Auth.user.getUser();
        MucTieu mt = mtkDAO.selectByid_MTTK(id, User);
        txtTenMTK.setText(mt.getTenMucTieu());
        txtGiaTri.setText(String.valueOf(mt.getGiaTri()));
        if (tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 3).equals("1 tháng")) {
            cboThoiGianTK.setSelectedIndex(0);
        } else if (tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 3).equals("3 tháng")) {
            cboThoiGianTK.setSelectedIndex(1);
        } else if (tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 3).equals("6 tháng")) {
            cboThoiGianTK.setSelectedIndex(2);
        } else {
            cboThoiGianTK.setSelectedIndex(3);
        }
    }

    //Tính ngày
    public void caCuLateDates() {

        MucTieu mt = (MucTieu) cboMucTietKiem.getSelectedItem();
        int currentMonth = Calendar.getInstance().get(Calendar.MONTH);
        int currentYear = Calendar.getInstance().get(Calendar.YEAR);
        //Ngày còn lại
        long sumDays = getSumDays(currentMonth, currentYear, mt.getThoiHan());
        long currentDate = (new Date().getTime() - mt.getNgayTao().getTime()) / (24 * 60 * 60 * 1000);
        long reSutl = sumDays - currentDate;
        lblNgayConLai.setText(String.valueOf(reSutl));
        //Deadline
        long day = mt.getNgayTao().getTime() + (sumDays * 24 * 60 * 60 * 1000);
        Calendar calendar = Calendar.getInstance();
        calendar.setTimeInMillis(day);
        txtThoiGian.setText(fmDate.toString(calendar.getTime(), "dd-MM-yyyy"));
        //textfied còn lại...
        pgbTienDo.setValue((int) ((int) (mt.getSoTienDaTK() * 100) / mt.getGiaTri()));
        txtTienDaTK.setText(String.format("%.0f", mt.getSoTienDaTK()) + " VND");
    }

    int getSumDays(int currentMonth, int currentYear, int month) {
        int sumDays = 0;
        for (int i = 0; i < month; i++) {
            sumDays += getNumberOfDays(currentMonth, currentYear);
            if (currentMonth >= 12) {
                currentYear++;
                currentMonth = 1;
            }
            currentMonth++;
        }
        return sumDays;

    }

    int getNumberOfDays(int month, int year) {
        if (month == 2) {
            if ((year % 400 == 0) || (year % 4 == 0 && year % 100 != 0)) {
                return 29;
            } else {
                return 28;
            }
        } else if (month == 1 || month == 3 || month == 5 || month == 7 || month == 8
                || month == 10 || month == 12) {
            return 31;
        } else {
            return 30;
        }
    }

    //Biểu đồ
    void pieChartMTK() {
        DefaultPieDataset dataset = new DefaultPieDataset();

        try {
            List<MucTieu> list = mtkDAO.selectMTK(Auth.user.getUser());
            for (MucTieu mt : list) {
                dataset.setValue(mt.getTenMucTieu(), mt.getGiaTri());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        JFreeChart chart = ChartFactory.createPieChart("", dataset, true, true, false);
//        ChartFrame chartFrame = new ChartFrame("yoyo", chart);
//        chartFrame.setVisible(true);
//        chartFrame.setSize(200,300);
        ChartPanel chartPanel = new ChartPanel(chart);
        pnlPieChart.removeAll();
        pnlPieChart.add(chartPanel, BorderLayout.CENTER);
        pnlPieChart.validate();
    }

    void barChartThuChi() {
        JFreeChart chart = ChartFactory.createBarChart("Thống kê thu chi 2020", "Tháng", "Tiền VNĐ", getDataThuChi(), PlotOrientation.VERTICAL, true, true, false);
//        ChartFrame chartFrame = new ChartFrame("yoyo", chart);
//        chartFrame.setVisible(true);
//        chartFrame.setSize(200, 300);

        final CategoryPlot plot = chart.getCategoryPlot();
        plot.setBackgroundPaint(new Color(0xEE, 0xEE, 0xFF));
        plot.setDomainAxisLocation(AxisLocation.BOTTOM_OR_RIGHT);

        final CategoryAxis domainAxis = plot.getDomainAxis();
        domainAxis.setCategoryLabelPositions(CategoryLabelPositions.DOWN_45);

        final LineAndShapeRenderer renderer2 = new LineAndShapeRenderer();
        renderer2.setToolTipGenerator(new StandardCategoryToolTipGenerator());
        plot.setRenderer(1, renderer2);
        plot.setDatasetRenderingOrder(DatasetRenderingOrder.REVERSE);

        ChartPanel chartPanel = new ChartPanel(chart);
        jPanel4.removeAll();
        jPanel4.add(chartPanel, BorderLayout.CENTER);
        jPanel4.validate();
    }

    CategoryDataset getDataThuChi() {
        final String series1 = "Tổng Thu";
        final String series2 = "Tổng Chi";
        // create the dataset...
        final DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        try {
            List<Object[]> list1 = tkctDAO.getThu(Auth.user.getUser());
            dataset.setValue(0, series1, "Tháng 1");
            dataset.setValue(0, series1, "Tháng 2");
            dataset.setValue(0, series1, "Tháng 3");
            dataset.setValue(0, series1, "Tháng 4");
            dataset.setValue(0, series1, "Tháng 5");
            dataset.setValue(0, series1, "Tháng 6");
            dataset.setValue(0, series1, "Tháng 7");
            dataset.setValue(0, series1, "Tháng 8");
            dataset.setValue(0, series1, "Tháng 9");
            dataset.setValue(0, series1, "Tháng 10");
            dataset.setValue(0, series1, "Tháng 11");
            dataset.setValue(0, series1, "Tháng 12");
            for (Object[] qlThu : list1) {

                dataset.addValue((Number) qlThu[1], series1, "Tháng " + (Comparable) qlThu[0]);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            List<Object[]> list2 = tkctDAO.getChi(Auth.user.getUser());
            for (Object[] qlChi : list2) {
                dataset.setValue((Number) qlChi[1], series2, "Tháng " + (Comparable) qlChi[0]);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return dataset;
    }

    void xoaGiaoDich() {
        Integer ID = (Integer) tblThuChi.getValueAt(tblThuChi.getSelectedRow(), 0);
        int id = (int) ID;
        try {
            capNhat_SoDu();
            tcDAO.delete(id);
            fillTableChiThu();
            MsgBox.alert(this, "XOá thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Lỗi!");
        }
    }

    void capNhat_SoDu() {
        NguoiDung nd = getSoDu();
        try {
            ndDAO.update(nd);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    NguoiDung getSoDu() {
        NguoiDung nd = ndDAO.selectByid(Auth.user.getUser());
        double tien = (double) tblThuChi.getValueAt(tblThuChi.getSelectedRow(), 3);
        double soDu = nd.getSoDu();
        if (tblThuChi.getValueAt(tblThuChi.getSelectedRow(), 4).equals("Thu")) {
            soDu -= tien;
        } else {
            soDu += tien;
        }
        nd.setSoDu(soDu);
        return nd;
    }

    void getInFoND() {
        NguoiDung nd = ndDAO.selectByid(Auth.user.getUser());
        txtIDNguoiDung.setText(nd.getUser());
        txtHoTen.setText(nd.getTenND());
        txtSoDu.setText(String.valueOf(nd.getSoDu()));
        if (nd.isGioiTinh()) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
    }

    NguoiDung setInFoND() {
        NguoiDung nd = new NguoiDung();
        nd.setUser(Auth.user.getUser());
        nd.setTenND(txtHoTen.getText());
        nd.setGioiTinh(rdoNam.isSelected());
        nd.setGioiTinh(!rdoNam.isSelected());
        nd.setSoDu(Double.valueOf(Auth.user.getSoDu()));
        nd.setMatKhau(Auth.user.getMatKhau());
        return nd;
    }

    void upDateInFoND() {
        NguoiDung nd = setInFoND();
        try {
            ndDAO.update1(nd);
            MsgBox.alert(this, "Update thành công");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
