/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.UI;

import com.dao.LichSuDAO;
import com.dao.MucTieuTietKiemDAO;
import com.dao.ThongKe_ThuChi_DAO;
import com.entity.LichSuTK;
import com.entity.MucTieu;
import com.entity.NguoiDung;
import com.entity.ThuChi;
import com.entity.TongThuChi;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Year;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ProgressBar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JProgressBar;
import javax.swing.KeyStroke;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.AxisLocation;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.labels.StandardCategoryToolTipGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.DatasetRenderingOrder;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DatasetGroup;
import org.jfree.data.general.DefaultPieDataset;
import util.Auth;
import util.JDBC;
import util.MsgBox;
import util.setColorSystem;
import utils.fmDate;

/**
 *
 * @author trantrung
 */
public class QuanLy extends javax.swing.JFrame {

    /**
     * Creates new form QuanLy
     */
    public QuanLy() {
        initComponents();
        init();
        tblDanhSach.getTableHeader().setOpaque(false);
        tblDanhSach.getTableHeader().setBackground(new Color(249,247,207));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBg = new javax.swing.JPanel();
        pnlleft = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlKeHoach = new javax.swing.JPanel();
        lblLogoQL = new javax.swing.JLabel();
        lblQuanLy = new javax.swing.JLabel();
        pnlThongKe = new javax.swing.JPanel();
        lblThuChi1 = new javax.swing.JLabel();
        lblLogoGD1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        pnlTabs = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        pnlTab1 = new javax.swing.JPanel();
        pnltop = new javax.swing.JPanel();
        lblTenMT = new javax.swing.JLabel();
        lblTenMT1 = new javax.swing.JLabel();
        lblTenMT2 = new javax.swing.JLabel();
        txtTenMTK = new javax.swing.JTextField();
        txtGiaTri = new javax.swing.JTextField();
        cboThoiGianTK = new javax.swing.JComboBox<>();
        pnlButton = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        btnThem = new javax.swing.JLabel();
        btnSua = new javax.swing.JLabel();
        btnXoa = new javax.swing.JLabel();
        btnTietKiem = new javax.swing.JLabel();
        pnlbottom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblMucTietKiem = new javax.swing.JLabel();
        cboMucTietKiem = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        pgbTienDo = new javax.swing.JProgressBar();
        lblTienDaTK = new javax.swing.JLabel();
        txtTienDaTK = new javax.swing.JTextField();
        lblThoiGianCon = new javax.swing.JLabel();
        txtThoiGian = new javax.swing.JTextField();
        lblNgayConLai = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlPieChart = new javax.swing.JPanel();
        pnlTab3 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLichSu = new javax.swing.JTable();
        pnlTab4 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSoDu = new javax.swing.JLabel();
        lblThemGiaoDich = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThuChi = new javax.swing.JTable();
<<<<<<< HEAD
=======
        jPanel4 = new javax.swing.JPanel();
>>>>>>> dabe126d91849ad633e59d8ed6243386303f8651
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBg.setPreferredSize(new java.awt.Dimension(700, 474));
        pnlBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlleft.setBackground(new java.awt.Color(154, 211, 188));
        pnlleft.setPreferredSize(new java.awt.Dimension(150, 100));
        pnlleft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setText("Logo");
        pnlleft.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        pnlKeHoach.setBackground(new java.awt.Color(154, 211, 188));
        pnlKeHoach.setPreferredSize(new java.awt.Dimension(150, 40));
        pnlKeHoach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlKeHoachMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlKeHoachMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlKeHoachMouseEntered(evt);
            }
        });
        pnlKeHoach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoQL.setBackground(new java.awt.Color(255, 255, 255));
        lblLogoQL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home_25px.png"))); // NOI18N
        pnlKeHoach.add(lblLogoQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 40));

        lblQuanLy.setBackground(new java.awt.Color(204, 204, 204));
        lblQuanLy.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        lblQuanLy.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLy.setText("Mục TK");
        pnlKeHoach.add(lblQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 40));

        pnlleft.add(pnlKeHoach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 150, 40));

        pnlThongKe.setBackground(new java.awt.Color(154, 211, 188));
        pnlThongKe.setPreferredSize(new java.awt.Dimension(150, 40));
        pnlThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseEntered(evt);
            }
        });
        pnlThongKe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThuChi1.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        lblThuChi1.setForeground(new java.awt.Color(255, 255, 255));
        lblThuChi1.setText("Thu/Chi");
        pnlThongKe.add(lblThuChi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        lblLogoGD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/currency_exchange_25px.png"))); // NOI18N
        pnlThongKe.add(lblLogoGD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 6, -1, -1));

        pnlleft.add(pnlThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 150, 40));

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlleft.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        pnlBg.add(pnlleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 470));

        pnlTabs.setLayout(new java.awt.CardLayout());

        pnltop.setBackground(new java.awt.Color(219, 246, 233));
        pnltop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTenMT.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        lblTenMT.setForeground(new java.awt.Color(51, 51, 51));
        lblTenMT.setText("Thời gian tiết kiệm:");
        pnltop.add(lblTenMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        lblTenMT1.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        lblTenMT1.setForeground(new java.awt.Color(51, 51, 51));
        lblTenMT1.setText("Tên mục tiết kiệm:");
        pnltop.add(lblTenMT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblTenMT2.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        lblTenMT2.setForeground(new java.awt.Color(51, 51, 51));
        lblTenMT2.setText("Giá trị:");
        pnltop.add(lblTenMT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txtTenMTK.setPreferredSize(new java.awt.Dimension(140, 24));
        pnltop.add(txtTenMTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, 30));

        txtGiaTri.setPreferredSize(new java.awt.Dimension(140, 24));
        pnltop.add(txtGiaTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 140, 30));

        cboThoiGianTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 tháng", "3 tháng", "6 tháng", "12 tháng" }));
        pnltop.add(cboThoiGianTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 140, 30));

        pnlButton.setBackground(new java.awt.Color(219, 246, 233));
        pnlButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(219, 246, 233));

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(lblExit)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlButton.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/createMT.png"))); // NOI18N
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemMouseExited(evt);
            }
        });
        pnlButton.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/createMT – 1.png"))); // NOI18N
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuaMouseExited(evt);
            }
        });
        pnlButton.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/createMT – 2.png"))); // NOI18N
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaMouseExited(evt);
            }
        });
        pnlButton.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        btnTietKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/createMT – 3.png"))); // NOI18N
        btnTietKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTietKiemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTietKiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTietKiemMouseExited(evt);
            }
        });
        pnlButton.add(btnTietKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        pnltop.add(pnlButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 160, 190));

        pnlbottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDanhSach.setBackground(new java.awt.Color(204, 204, 204));
        tblDanhSach.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên mục tiêt kiệm", "Giá trị", "Thời gian tiết kiệm", "Số tiền đã tiết kiệm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);

        pnlbottom.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 250));

        javax.swing.GroupLayout pnlTab1Layout = new javax.swing.GroupLayout(pnlTab1);
        pnlTab1.setLayout(pnlTab1Layout);
        pnlTab1Layout.setHorizontalGroup(
            pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTab1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnltop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlbottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlTab1Layout.setVerticalGroup(
            pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addGap(0, 471, Short.MAX_VALUE)
=======
            .addGap(0, 446, Short.MAX_VALUE)
>>>>>>> dabe126d91849ad633e59d8ed6243386303f8651
            .addGroup(pnlTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTab1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnltop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(pnlbottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Tích luỹ", pnlTab1);

        lblMucTietKiem.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        lblMucTietKiem.setText("Mục tiết kiệm:");

        cboMucTietKiem.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        cboMucTietKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMucTietKiemActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pgbTienDo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pgbTienDo.setEnabled(false);
        pgbTienDo.setPreferredSize(new java.awt.Dimension(146, 200));
        pgbTienDo.setStringPainted(true);

        lblTienDaTK.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        lblTienDaTK.setText("Số tiền đã tiết kiệm được:");

        lblThoiGianCon.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        lblThoiGianCon.setText("Tiết kiệm đến ngày:");

        lblNgayConLai.setText("jLabel4");

        jLabel4.setText("Tiến độ:");

        pnlPieChart.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlPieChart.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNgayConLai)
                    .addComponent(lblTienDaTK)
                    .addComponent(txtTienDaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThoiGianCon)
                    .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(pgbTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlPieChart, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(pgbTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTienDaTK)
                .addGap(17, 17, 17)
                .addComponent(txtTienDaTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblThoiGianCon)
                .addGap(14, 14, 14)
                .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNgayConLai)
<<<<<<< HEAD
                .addContainerGap(117, Short.MAX_VALUE))
=======
                .addContainerGap(129, Short.MAX_VALUE))
>>>>>>> dabe126d91849ad633e59d8ed6243386303f8651
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPieChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblMucTietKiem)
                .addGap(35, 35, 35)
                .addComponent(cboMucTietKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMucTietKiem)
                    .addComponent(cboMucTietKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Thống kê mục tiết kiệm", jPanel3);

        btnTimKiem.setFont(new java.awt.Font("Quicksand", 0, 13)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tblLichSu.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        tblLichSu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mục tiết kiệm", "Ngày ", "Số tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblLichSu);

        javax.swing.GroupLayout pnlTab3Layout = new javax.swing.GroupLayout(pnlTab3);
        pnlTab3.setLayout(pnlTab3Layout);
        pnlTab3Layout.setHorizontalGroup(
            pnlTab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTab3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlTab3Layout.createSequentialGroup()
<<<<<<< HEAD
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
=======
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
>>>>>>> dabe126d91849ad633e59d8ed6243386303f8651
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimKiem)))
                .addContainerGap())
        );
        pnlTab3Layout.setVerticalGroup(
            pnlTab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTab3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Lịch sử", pnlTab3);

        pnlTabs.add(jTabbedPane2, "card1");

        jLabel1.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        jLabel1.setText("Số dư:");

        lblSoDu.setText("jLabel2");

        lblThemGiaoDich.setText("Thêm giao dịch");
        lblThemGiaoDich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThemGiaoDichMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThemGiaoDichMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThemGiaoDichMouseEntered(evt);
            }
        });

        tblThuChi.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        tblThuChi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên giao dịch", "Ngày", "Số tiền", "Loại giao dịch"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblThuChi);
<<<<<<< HEAD
=======

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblSoDu, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(lblThemGiaoDich)
                .addGap(68, 68, 68))
            .addComponent(jScrollPane3)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSoDu)
                    .addComponent(lblThemGiaoDich))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jTabbedPane3.addTab("Giao Dịch", jPanel6);

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new java.awt.BorderLayout());
        jTabbedPane3.addTab("Thống kê Thu/Chi", jPanel4);
>>>>>>> dabe126d91849ad633e59d8ed6243386303f8651

        javax.swing.GroupLayout pnlTab4Layout = new javax.swing.GroupLayout(pnlTab4);
        pnlTab4.setLayout(pnlTab4Layout);
        pnlTab4Layout.setHorizontalGroup(
            pnlTab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTab4Layout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblSoDu, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblThemGiaoDich)
                .addGap(62, 62, 62))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
=======
                .addGap(12, 12, 12)
                .addComponent(jTabbedPane3)
                .addContainerGap())
>>>>>>> dabe126d91849ad633e59d8ed6243386303f8651
        );
        pnlTab4Layout.setVerticalGroup(
            pnlTab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTab4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTabs.add(pnlTab4, "card2");

        pnlBg.add(pnlTabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 550, 470));

        getContentPane().add(pnlBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 30, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlKeHoachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKeHoachMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setColor(pnlKeHoach);
    }//GEN-LAST:event_pnlKeHoachMouseEntered

    private void pnlKeHoachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKeHoachMouseExited
        setColorSystem cl = new setColorSystem();
        cl.resetColor(pnlKeHoach);
    }//GEN-LAST:event_pnlKeHoachMouseExited

    private void pnlKeHoachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKeHoachMouseClicked
        cardLayout.show(pnlTabs, "card1");
        thongKeMTK();
    }//GEN-LAST:event_pnlKeHoachMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblExit);
    }//GEN-LAST:event_lblExitMouseExited

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblExit);
    }//GEN-LAST:event_lblExitMouseEntered

    private void pnlThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setColor(pnlThongKe);
    }//GEN-LAST:event_pnlThongKeMouseEntered

    private void pnlThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseExited
        setColorSystem cl = new setColorSystem();
        cl.resetColor(pnlThongKe);
    }//GEN-LAST:event_pnlThongKeMouseExited

    private void pnlThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseClicked
        cardLayout.show(pnlTabs, "card2");
        thongKeGiaoDich();
    }//GEN-LAST:event_pnlThongKeMouseClicked

    private void btnThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setBorder(btnThem);
    }//GEN-LAST:event_btnThemMouseEntered

    private void btnThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseExited
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(btnThem);
    }//GEN-LAST:event_btnThemMouseExited

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        if (checkError()) {
            addMtkToDaTaBase();
        }
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnSuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setBorder(btnSua);
    }//GEN-LAST:event_btnSuaMouseEntered

    private void btnSuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseExited
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(btnSua);
    }//GEN-LAST:event_btnSuaMouseExited

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        if (checkError()) {
            updateMtkToDaTaBase();
        }
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setBorder(btnXoa);
    }//GEN-LAST:event_btnXoaMouseEntered

    private void btnXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseExited
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(btnXoa);
    }//GEN-LAST:event_btnXoaMouseExited

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        deleteMtk();
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnTietKiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTietKiemMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setBorder(btnTietKiem, 240, 84, 84);
    }//GEN-LAST:event_btnTietKiemMouseEntered

    private void btnTietKiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTietKiemMouseExited

        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(btnTietKiem);
    }//GEN-LAST:event_btnTietKiemMouseExited

    private void btnTietKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTietKiemMouseClicked
        new TietKiem().setVisible(true);
    }//GEN-LAST:event_btnTietKiemMouseClicked

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        selectForm();
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void cboMucTietKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMucTietKiemActionPerformed
        if (cboMucTietKiem.getSelectedIndex() != -1) {
            thongKe();
        }
    }//GEN-LAST:event_cboMucTietKiemActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        fillTableLichSu();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        thongKeGiaoDich();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void lblThemGiaoDichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemGiaoDichMouseClicked
        new GiaoDich().setVisible(true);
    }//GEN-LAST:event_lblThemGiaoDichMouseClicked

    private void lblThemGiaoDichMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemGiaoDichMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblThemGiaoDich, 0, 0, 0);
    }//GEN-LAST:event_lblThemGiaoDichMouseEntered

    private void lblThemGiaoDichMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemGiaoDichMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblThemGiaoDichMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel btnSua;
    private javax.swing.JLabel btnThem;
    private javax.swing.JLabel btnTietKiem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel btnXoa;
    private javax.swing.JComboBox<String> cboMucTietKiem;
    private javax.swing.JComboBox<String> cboThoiGianTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
<<<<<<< HEAD
    private javax.swing.JTabbedPane jTabbedPane1;
=======
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
>>>>>>> dabe126d91849ad633e59d8ed6243386303f8651
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoGD1;
    private javax.swing.JLabel lblLogoQL;
    private javax.swing.JLabel lblMucTietKiem;
    private javax.swing.JLabel lblNgayConLai;
    private javax.swing.JLabel lblQuanLy;
    private javax.swing.JLabel lblSoDu;
    private javax.swing.JLabel lblTenMT;
    private javax.swing.JLabel lblTenMT1;
    private javax.swing.JLabel lblTenMT2;
    private javax.swing.JLabel lblThemGiaoDich;
    private javax.swing.JLabel lblThoiGianCon;
    private javax.swing.JLabel lblThuChi1;
    private javax.swing.JLabel lblTienDaTK;
    private javax.swing.JProgressBar pgbTienDo;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlKeHoach;
    private javax.swing.JPanel pnlPieChart;
    private javax.swing.JPanel pnlTab1;
    private javax.swing.JPanel pnlTab3;
    private javax.swing.JPanel pnlTab4;
    private javax.swing.JPanel pnlTabs;
    private javax.swing.JPanel pnlThongKe;
    private javax.swing.JPanel pnlbottom;
    private javax.swing.JPanel pnlleft;
    private javax.swing.JPanel pnltop;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTable tblLichSu;
    private javax.swing.JTable tblThuChi;
    private javax.swing.JTextField txtGiaTri;
    private javax.swing.JTextField txtTenMTK;
    private javax.swing.JTextField txtThoiGian;
    private javax.swing.JTextField txtTienDaTK;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    CardLayout cardLayout;
    MucTieuTietKiemDAO mtkDAO = new MucTieuTietKiemDAO();
    LichSuDAO lsDAO = new LichSuDAO();
    ThongKe_ThuChi_DAO tkctDAO= new ThongKe_ThuChi_DAO();

    void init() {
        this.setResizable(true);
        this.setLocationRelativeTo(null);
//        this.setBackground(new Color(0, 0, 0, 0));
//        pnlBg.setBackground(new Color(0, 0, 0, 0));
        cardLayout = (CardLayout) pnlTabs.getLayout();
        fillTableMucTietKiem();
        fillComboBox();
        mouseHover();
        fillTableLichSu();
        inFoGiaoDich();
        fillTableChiThu();
    }

    public void mouseHover() {
        pnlKeHoach.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        pnlThongKe.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
    }

    public void fillTableMucTietKiem() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSach.getModel();
        model.setRowCount(0);
        try {
            List<MucTieu> list = mtkDAO.selectMTK(Auth.user.getUser());
            for (MucTieu mt : list) {
                Object row[] = {
                    mt.getIdMucTieu(), mt.getTenMucTieu(), mt.getGiaTri(), mt.getThoiHan() + " tháng", mt.getSoTienDaTK()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Loi truy van du lieu");
            e.printStackTrace();
        }
    }

    public void fillTableLichSu() {
        DefaultTableModel model = (DefaultTableModel) tblLichSu.getModel();
        model.setRowCount(0);
        if (txtTimKiem.getText().equals("")) {
            try {
                List<Object[]> list = lsDAO.getLichSu(Auth.user.getUser());
                for (Object[] ls : list) {
                    model.addRow(ls);
                }
                tblLichSu.setModel(model);
            } catch (Exception e) {
                MsgBox.alert(this, "Loi truy van du lieu");
                e.printStackTrace();
            }
        } else {
            try {
                List<Object[]> list = lsDAO.getLichSu1(Auth.user.getUser(), txtTimKiem.getText().trim());
                for (Object[] ls : list) {
                    model.addRow(ls);
                }
            } catch (Exception e) {
                MsgBox.alert(this, "Loi truy van du lieu");
                e.printStackTrace();
            }
        }
    }

    public void addMtkToDaTaBase() {
        MucTieu mt = getInFo();
        try {
            mtkDAO.insert(mt);
            fillTableMucTietKiem();
            fillComboBox();
        } catch (Exception e) {
            MsgBox.alert(this, "Loi roi ku");
        }
    }

    public void updateMtkToDaTaBase() {
        MucTieu mt = upDateInFo();
        try {
            mtkDAO.update(mt);
            fillTableMucTietKiem();
            clear();
        } catch (Exception e) {
            MsgBox.alert(this, "Loi roi ku");
        }
    }

    public void deleteMtk() {
        if (Auth.user.getUser().equals("")) {
            MsgBox.alert(this, "Dang nhap de co the xoa");
        } else if (MsgBox.confirm(this, "That su muon xoa ?")) {
            try {
                int row = (int) (tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 0));
                mtkDAO.delete(row);
                MsgBox.alert(this, "Xoa thanh cong");
                fillTableMucTietKiem();
                fillComboBox();
            } catch (Exception e) {
                MsgBox.alert(this, "Loi roi ku");
                e.printStackTrace();
            }
        }
    }

    public void clear() {
        txtTenMTK.setText("");
        txtThoiGian.setText("");
        txtTienDaTK.setText("");
        txtGiaTri.setText("");
        cboThoiGianTK.setSelectedIndex(0);
    }

    MucTieu getInFo() {
        MucTieu mt = new MucTieu();
        String arr = (String) cboThoiGianTK.getSelectedItem();
        String ar[] = arr.split(" ");
        mt.setUsername(Auth.user.getUser());
        mt.setTenMucTieu(txtTenMTK.getText());
        mt.setGiaTri(Double.parseDouble(txtGiaTri.getText()));
        mt.setThoiHan(Integer.valueOf(ar[0]));
        return mt;
    }

    MucTieu upDateInFo() {
        MucTieu mt = new MucTieu();
        try {
            String arr = (String) cboThoiGianTK.getSelectedItem();
            String ar[] = arr.split(" ");
            mt.setTenMucTieu(txtTenMTK.getText());
            mt.setGiaTri(Double.parseDouble(txtGiaTri.getText()));
            mt.setThoiHan(Integer.valueOf(ar[0]));
            Double value = (double) tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 4);
            mt.setSoTienDaTK(value);
            int id = (int) tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 0);
            mt.setIdMucTieu(id);
        } catch (Exception e) {
            MsgBox.alert(this, "Cap nhat loi, vui long cap nhat lai");
        }
        return mt;
    }

    void selectForm() {
        int id = (int) tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 0);
        String User = Auth.user.getUser();
        MucTieu mt = mtkDAO.selectByid_MTTK(id, User);
        txtTenMTK.setText(mt.getTenMucTieu());
        txtGiaTri.setText(String.valueOf(mt.getGiaTri()));
        if (tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 3).equals("1 tháng")) {
            cboThoiGianTK.setSelectedIndex(0);
        } else if (tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 3).equals("3 tháng")) {
            cboThoiGianTK.setSelectedIndex(1);
        } else if (tblDanhSach.getValueAt(tblDanhSach.getSelectedRow(), 3).equals("6 tháng")) {
            cboThoiGianTK.setSelectedIndex(2);
        } else {
            cboThoiGianTK.setSelectedIndex(3);
        }
    }

    boolean checkError() {
        if (txtGiaTri.getText().matches(".*[a-zA-Z].*")) {
            MsgBox.alert(this, "Khong dc dien ki tu vao o gia tri");
            return false;
        } else if (txtTenMTK.getText().equals("") || txtGiaTri.getText().equals("")) {
            MsgBox.alert(this, "khong duoc de trong");
            return false;
        } else if (Double.valueOf(txtGiaTri.getText()) < 0) {
            MsgBox.alert(this, "khong duoc nhap so am");
            return false;
        }
        return true;
    }

    boolean noTif() {
        List<MucTieu> list = mtkDAO.selectMTK(Auth.user.getUser());
        for (MucTieu mt : list) {
            if (mt.getGiaTri() >= mt.getSoTienDaTK()) {
                MsgBox.alert(this, "Ban da tiet kiem du");
                return true;
            }
        }
        return false;
    }

    public void fillComboBox() {
        DefaultComboBoxModel combobox = (DefaultComboBoxModel) cboMucTietKiem.getModel();
        combobox.removeAllElements();
        List<MucTieu> list = mtkDAO.selectMTK(Auth.user.getUser());
        for (MucTieu mt : list) {
            combobox.addElement(mt);
        }
    }

    public void thongKe() {

        MucTieu mt = (MucTieu) cboMucTietKiem.getSelectedItem();
        int currentMonth = Calendar.getInstance().get(Calendar.MONTH);
        int currentYear = Calendar.getInstance().get(Calendar.YEAR);
        //Ngày còn lại
        long sumDays = getSumDays(currentMonth, currentYear, mt.getThoiHan());
        long currentDate = (new Date().getTime() - mt.getNgayTao().getTime()) / (24 * 60 * 60 * 1000);
        long reSutl = sumDays - currentDate;
        lblNgayConLai.setText(String.valueOf(reSutl));
        //Deadline
        long day = mt.getNgayTao().getTime() + (sumDays * 24 * 60 * 60 * 1000);
        Calendar calendar = Calendar.getInstance();
        calendar.setTimeInMillis(day);
        txtThoiGian.setText(fmDate.toString(calendar.getTime(), "dd-MM-yyyy"));
        //textfied còn lại...
        pgbTienDo.setValue((int) ((int) (mt.getSoTienDaTK() * 100) / mt.getGiaTri()));
        txtTienDaTK.setText(String.valueOf(mt.getSoTienDaTK()));
    }

    int getSumDays(int currentMonth, int currentYear, int month) {
        int sumDays = 0;
        for (int i = 0; i < month; i++) {
            sumDays += getNumberOfDays(currentMonth, currentYear);
            if (currentMonth >= 12) {
                currentYear++;
                currentMonth = 1;
            }
            currentMonth++;
        }
        return sumDays;

    }

    int getNumberOfDays(int month, int year) {
        if (month == 2) {
            if ((year % 400 == 0) || (year % 4 == 0 && year % 100 != 0)) {
                return 29;
            } else {
                return 28;
            }
        } else if (month == 1 || month == 3 || month == 5 || month == 7 || month == 8
                || month == 10 || month == 12) {
            return 31;
        } else {    
            return 30;
        }
    }

    void thongKeMTK() {
        DefaultPieDataset dataset = new DefaultPieDataset();

        try {
            List<MucTieu> list = mtkDAO.selectMTK(Auth.user.getUser());
            for (MucTieu mt : list) {
                dataset.setValue(mt.getTenMucTieu(), mt.getGiaTri());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        JFreeChart chart = ChartFactory.createPieChart("", dataset, true, true, false);
//        ChartFrame chartFrame = new ChartFrame("yoyo", chart);
//        chartFrame.setVisible(true);
//        chartFrame.setSize(200,300);
        ChartPanel chartPanel = new ChartPanel(chart);
        pnlPieChart.removeAll();
        pnlPieChart.add(chartPanel, BorderLayout.CENTER);
        pnlPieChart.validate();
    }

    void thongKeGiaoDich() {
        JFreeChart chart = ChartFactory.createBarChart("Thống kê thu chi 2020", "Tháng", "Tiền VNĐ", nhomThuChi(), PlotOrientation.VERTICAL, true, true, false);
//        ChartFrame chartFrame = new ChartFrame("yoyo", chart);
//        chartFrame.setVisible(true);
//        chartFrame.setSize(200, 300);
        
        final CategoryPlot plot = chart.getCategoryPlot();
        plot.setBackgroundPaint(new Color(0xEE, 0xEE, 0xFF));
        plot.setDomainAxisLocation(AxisLocation.BOTTOM_OR_RIGHT);
        
        final CategoryAxis domainAxis = plot.getDomainAxis();
        domainAxis.setCategoryLabelPositions(CategoryLabelPositions.DOWN_45);

        final LineAndShapeRenderer renderer2 = new LineAndShapeRenderer();
        renderer2.setToolTipGenerator(new StandardCategoryToolTipGenerator());
        plot.setRenderer(1, renderer2);
        plot.setDatasetRenderingOrder(DatasetRenderingOrder.REVERSE);
        
        ChartPanel chartPanel = new ChartPanel(chart);
        jPanel4.removeAll();
        jPanel4.add(chartPanel, BorderLayout.CENTER);
        jPanel4.validate();
    }

    CategoryDataset nhomThuChi() {
        final String series1 = "Tổng Thu";
        final String series2 = "Tổng Chi";
        // create the dataset...
        final DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        try {
            List<Object[]> list1 = tkctDAO.getThu(Auth.user.getUser());
            for (Object[] qlThu : list1) {
                dataset.setValue((Number) qlThu[1], series1,"Tháng " + (Comparable) qlThu[0]);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        try {
            List<Object[]> list2 = tkctDAO.getChi(Auth.user.getUser());
            for (Object[] qlChi : list2) {
                dataset.setValue((Number) qlChi[1], series2,"Tháng " + (Comparable) qlChi[0]);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return dataset;
    }
    
    void inFoGiaoDich(){
        NguoiDung nd = new NguoiDung();
        double values = nd.getSoDu();
        lblSoDu.setText(String.valueOf(values));
    }
    void fillTableChiThu(){
        DefaultTableModel model = (DefaultTableModel) tblThuChi.getModel();
        model.setRowCount(0);
        try {
            List<Object[]> list = tkctDAO.LichSu_ThuChi(Auth.user.getUser());
            for (Object[] ls : list) {
                model.addRow(ls);
            }
            tblThuChi.setModel(model);
        } catch (Exception e) {
            MsgBox.alert(this, "Loi truy van du lieu");
            e.printStackTrace();
        }
    }
}
