/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.UI;

import com.dao.MucTieuTietKiemDAO;
import com.entity.MucTieu;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import util.Auth;
import util.MsgBox;
import util.setColorSystem;

/**
 *
 * @author trantrung
 */
public class TietKiem extends javax.swing.JFrame {

    /**
     * Creates new form TietKiem
     */
    public TietKiem() {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
        this.setBackground(new Color(0, 0, 0, 0));
        fillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMucTietKiem = new javax.swing.JLabel();
        cboMTK = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtGiaTri = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtThoiGian = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoTienTietKiem = new javax.swing.JTextField();
        btnTietKiem = new javax.swing.JButton();
        lblExit = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(302, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMucTietKiem.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        lblMucTietKiem.setText("Mục tiết kiệm:");
        jPanel1.add(lblMucTietKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        cboMTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMTKActionPerformed(evt);
            }
        });
        jPanel1.add(cboMTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, -1));

        jLabel1.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        jLabel1.setText("Giá trị:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtGiaTri.setEditable(false);
        txtGiaTri.setPreferredSize(new java.awt.Dimension(14, 30));
        jPanel1.add(txtGiaTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, -1));

        jLabel3.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        jLabel3.setText("Thời gian tiết kiệm:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txtThoiGian.setEditable(false);
        txtThoiGian.setPreferredSize(new java.awt.Dimension(14, 30));
        jPanel1.add(txtThoiGian, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 280, -1));

        jLabel4.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        jLabel4.setText("Số tiền tiết kiệm:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        txtSoTienTietKiem.setPreferredSize(new java.awt.Dimension(14, 30));
        jPanel1.add(txtSoTienTietKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 280, -1));

        btnTietKiem.setText("Tiết kiệm");
        btnTietKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTietKiemActionPerformed(evt);
            }
        });
        jPanel1.add(btnTietKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
        });
        jPanel1.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/background1.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        this.dispose();
        new QuanLy().fillTableMucTietKiem();
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        setColorSystem cl = new setColorSystem();
        cl.reSetBorder(lblExit);
    }//GEN-LAST:event_lblExitMouseExited

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        setColorSystem cl = new setColorSystem();
        cl.setBorder(lblExit);
    }//GEN-LAST:event_lblExitMouseEntered

    private void cboMTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMTKActionPerformed
        fillInFo();
    }//GEN-LAST:event_cboMTKActionPerformed

    private void btnTietKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTietKiemActionPerformed
        if(checkError()){
            insert();
        }
    }//GEN-LAST:event_btnTietKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TietKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TietKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TietKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TietKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TietKiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnTietKiem;
    private javax.swing.JComboBox<String> cboMTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMucTietKiem;
    private javax.swing.JTextField txtGiaTri;
    private javax.swing.JTextField txtSoTienTietKiem;
    private javax.swing.JTextField txtThoiGian;
    // End of variables declaration//GEN-END:variables
    MucTieuTietKiemDAO mtkdao = new MucTieuTietKiemDAO();

    public void fillComboBox() {
        DefaultComboBoxModel combobox = (DefaultComboBoxModel) cboMTK.getModel();
        combobox.removeAllElements();
        List<MucTieu> list = mtkdao.selectMTK(Auth.user.getUser());
        for (MucTieu mt : list) {
            combobox.addElement(mt);
        }
    }

    public void fillInFo() {
        MucTieu muctieu = (MucTieu) cboMTK.getSelectedItem();
        txtGiaTri.setText(String.valueOf(muctieu.getGiaTri()));
        txtThoiGian.setText(String.valueOf(muctieu.getThoiHan()) + " tháng");
    }

    MucTieu getInFo() {
        MucTieu muctieu = (MucTieu) cboMTK.getSelectedItem();
        double newPrice = muctieu.getSoTienDaTK();
        newPrice += Double.valueOf(txtSoTienTietKiem.getText());
        muctieu.setSoTienDaTK(newPrice);
        return muctieu;
    }
    
        void insert() {
        MucTieu mt = getInFo();
        try {
            mtkdao.update(mt);
            MsgBox.alert(this, "Tiet kiem");
            new QuanLy().setVisible(false);new QuanLy().setVisible(true);
        } catch (Exception e) {
            MsgBox.alert(this, "Co loi xay ra");
            System.out.println(e.getMessage());
        }
    }

        boolean checkError(){
            if(txtSoTienTietKiem.getText().equals("")){
                MsgBox.alert(this, "So tien can tiet kiem dang bo trong");
                return false;
            } else if(Double.valueOf(txtSoTienTietKiem.getText())<0){
                MsgBox.alert(this, "Khong the nhap so am");
                return false;
            }
            return true;
        }
}
